services:
  verandb:
    build: https://github.com/wichmann/veranstaltungsdatenbank.git
    image: verandb
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - verandb_data:/app

volumes:
  verandb_data:
